<?php

namespace App\Models\STXI\CEISA40;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class HEADERCIESA extends Model
{
    use HasFactory;
    protected $connection = 'sqlsrv_ceisa40';
    protected $table = '01_HEADER';
    protected $primaryKey = '[NOMOR AJU]';
    protected $fillable = [
        'NOMOR AJU',
        'KODE DOKUMEN',
        'KODE KANTOR',
        'KODE KANTOR BONGKAR',
        'KODE KANTOR PERIKSA',
        'KODE KANTOR TUJUAN',
        'KODE KANTOR EKSPOR',
        'KODE JENIS IMPOR',
        'KODE JENIS EKSPOR',
        'KODE JENIS TPB',
        'KODE JENIS PLB',
        'KODE JENIS PROSEDUR',
        'KODE TUJUAN PEMASUKAN',
        'KODE TUJUAN PENGIRIMAN',
        'KODE TUJUAN TPB',
        'KODE CARA DAGANG',
        'KODE CARA BAYAR',
        'KODE CARA BAYAR LAINNYA',
        'KODE GUDANG ASAL 19',
        'KODE GUDANG TUJUAN 20',
        'KODE JENIS KIRIM',
        'KODE JENIS PENGIRIMAN',
        'KODE KATEGORI EKSPOR',
        'KODE KATEGORI MASUK FTZ',
        'KODE KATEGORI KELUAR FTZ',
        'KODE KATEGORI BARANG FTZ',
        'KODE LOKASI',
        'KODE LOKASI BAYAR',
        'LOKASI ASAL',
        'LOKASI TUJUAN',
        'KODE DAERAH ASAL',
        'KODE GUDANG ASAL 32',
        'KODE GUDANG TUJUAN 33',
        'KODE NEGARA TUJUAN',
        'KODE TUTUP PU',
        'NOMOR BC11',
        'TANGGAL BC11',
        'NOMOR POS',
        'NOMOR SUB POS',
        'KODE PELABUHAN BONGKAR',
        'KODE PELABUHAN MUAT',
        'KODE PELABUHAN MUAT AKHIR',
        'KODE PELABUHAN TRANSIT',
        'KODE PELABUHAN TUJUAN',
        'KODE PELABUHAN EKSPOR',
        'KODE TPS',
        'TANGGAL BERANGKAT',
        'TANGGAL EKSPOR',
        'TANGGAL MASUK',
        'TANGGAL MUAT',
        'TANGGAL TIBA',
        'TANGGAL PERIKSA',
        'TEMPAT STUFFING',
        'TANGGAL STUFFING',
        'KODE TANDA PENGAMAN',
        'JUMLAH TANDA PENGAMAN',
        'FLAG CURAH',
        'FLAG SDA',
        'FLAG VD',
        'FLAG AP BK',
        'FLAG MIGAS',
        'KODE ASURANSI',
        'ASURANSI 63',
        'NILAI BARANG',
        'NILAI INCOTERM',
        'NILAI MAKLON',
        'ASURANSI 67',
        'FREIGHT',
        'FOB',
        'BIAYA TAMBAHAN',
        'BIAYA PENGURANG',
        'VD',
        'CIF',
        'HARGA_PENYERAHAN',
        'NDPBM',
        'TOTAL DANA SAWIT',
        'DASAR PENGENAAN PAJAK',
        'NILAI JASA',
        'UANG MUKA',
        'BRUTO',
        'NETTO',
        'VOLUME',
        'KOTA PERNYATAAN',
        'TANGGAL PERNYATAAN',
        'NAMA PERNYATAAN',
        'JABATAN PERNYATAAN',
        'KODE VALUTA',
        'KODE INCOTERM',
        'KODE JASA KENA PAJAK',
        'NOMOR BUKTI BAYAR',
        'TANGGAL BUKTI BAYAR',
        'KODE JENIS NILAI',
        'KODE KANTOR MUAT',
        'NOMOR DAFTAR',
        'TANGGAL DAFTAR',
        'KODE ASAL BARANG FTZ',
        'KODE TUJUAN PENGELUARAN',
        'PPN PAJAK',
        'PPNBM PAJAK',
        'TARIF PPN PAJAK',
        'TARIF PPNBM PAJAK',
        'BARANG TIDAK BERWUJUD',
        'KODE JENIS PENGELUARAN',
        'BARANG KIRIMAN',
        'FLAG KONSOL',
        'KODE JENIS PENGANGKUTAN',
        'FLAG PROPORSIONAL NETTO',
        'Z_STATUS',
        'Z_UPDDT',
        'Z_UPDBY'
    ];
}
